// import { useCurrentImage } from "@/src/composables/useCurrentImage";
// import vtkImageData from "@kitware/vtk.js/Common/DataModel/ImageData";
// import vtkLabelMap from "@/src/vtk/LabelMap";
// import DicomChunkImage from "@/src/core/streaming/dicomChunkImage";
// import { Tags } from "@/src/core/dicomTags";
// import { readImage } from "@/src/io/readWriteImage";
// import { useImageCacheStore } from "../image-cache";
// import { SegmentGroupMetadata, toLabelMap, useSegmentGroupStore } from "../segmentGroups";

// const { VITE_FASTAPI_URL } = import.meta.env;

// const DENTAL_CLASS_MAP: Record<number, { name: string; color: [number, number, number, number] }> = {
//     1: { name: 'Crown', color: [227, 26, 28, 255] },             // API ID 0
//     2: { name: 'Alveolar_bone', color: [31, 120, 180, 255] },    // API ID 1
//     3: { name: 'Caries', color: [178, 223, 138, 255] },          // API ID 2
//     4: { name: 'Dentin', color: [51, 160, 44, 255] },            // API ID 3
//     5: { name: 'Pulp', color: [251, 154, 153, 255] },            // API ID 4
//     6: { name: 'Maxillary_sinus', color: [253, 191, 111, 255] }, // API ID 5
//     7: { name: 'Implant', color: [255, 127, 0, 255] },           // API ID 6
//     8: { name: 'Enamel', color: [202, 178, 214, 255] },          // API ID 7
//     9: { name: 'Post_and_core', color: [106, 61, 154, 255] },    // API ID 8
//     10: { name: 'Restoration', color: [255, 255, 153, 255] },    // API ID 9
//     11: { name: 'Periapical_lesion', color: [177, 89, 40, 255] }, // API ID 10
//     12: { name: 'Root_canal_filling', color: [166, 206, 227, 255] }, // API ID 11
//     13: { name: 'Mandibular_alveolar_nerve', color: [179, 226, 205, 255] }, // API ID 12
// };

// interface DicomImageData {
//     studyInstanceUID: string;
//     seriesInstanceUID: string;
//     sopInstanceUID: string;
// }

// // // TODO: will be removed later
// // function getVtiFile(): File {
// //     const vtiFileContent: string = `<?xml version="1.0"?>
// //     <VTKFile type="ImageData" version="0.1" byte_order="LittleEndian" header_type="UInt32" compressor="vtkZLibDataCompressor">
// //         <ImageData WholeExtent="0 812 0 613 0 0" Origin="0 0 0" Spacing="1 1 1" Direction="1 0 0 0 1 0 0 0 1">
// //             <Piece Extent="0 812 0 613 0 0">
// //                 <PointData Scalars="vtkDataArray1592">
// //                     <DataArray type="UInt8" Name="vtkDataArray1592" format="binary" RangeMin="0" RangeMax="0" NumberOfComponents="1">
// //                         6AEAAAAEAADuAQAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAASAAAAGQAAABcAAAAWAAAAHwAAABgAAAAYAAAAGQAAAB4AAAAYAAAAGAAAABkAAAAiAAAAGgAAABgAAAAaAAAAKAAAABoAAAAaAAAAHgAAACAAAAAaAAAAGwAAACEAAAAgAAAAGQAAABgAAAAbAAAAHwAAABkAAAAZAAAAHgAAABgAAAAYAAAAGQAAACEAAAAYAAAAGAAAABsAAAAnAAAAGwAAABsAAAAiAAAAJQAAABwAAAAhAAAAKwAAACUAAAAeAAAAGwAAACwAAAAiAAAAHwAAACEAAAArAAAAIQAAACEAAAAmAAAANAAAACIAAAAkAAAALwAAAC8AAAAhAAAAHgAAACkAAAAoAAAAJQAAACsAAAA8AAAANQAAACgAAAAoAAAAQgAAAD0AAAAwAAAALQAAADsAAAA4AAAALQAAADEAAAA1AAAAMgAAACwAAAA2AAAAQwAAADEAAAA1AAAAPgAAAEQAAAAzAAAANAAAAEgAAABHAAAAPQAAAD4AAAA9AAAAPAAAAC8AAAAxAAAATAAAADcAAAAvAAAANAAAAEoAAAA4AAAANAAAAEEAAABMAAAAPAAAADMAAABCAAAAQwAAADsAAAA0AAAAQQAAAEIAAAAxAAAALwAAAEcAAABOAAAAMgAAADEAAABGAAAARgAAADQAAAA2AAAARgAAADcAAAAxAAAANwAAADwAAAA0AAAALwAAADQAAABAAAAAMQAAADgAAABFAAAAQQAAADIAAAAtAAAANAAAADwAAAAmAAAALQAAADsAAABEAAAALgAAACkAAAA1AAAAJgAAACgAAAAqAAAAOwAAAC8AAAAnAAAAJgAAADUAAAAhAAAAGgAAAB4AAAAfAAAAIAAAACAAAAApAAAALQAAAB4AAAAcAAAAHwAAACMAAAAdAAAAGAAAACIAAAAhAAAAGwAAABoAAAAdAAAAGwAAABkAAAAZAAAAHwAAABsAAAAZAAAAGQAAABkAAAAWAAAAFwAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAA0AAAA=eJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIwYwIgGAASIABF4nGNkZBgFo2AUMDAwEgcG2pnUBQAubQAqeJxjGAWjgETASBIYaNeOAnwAAFKdAC94nGMYBTQEjKSDgXbyKBhRAACFSwA0eJxjGByAES/Ao3oA3DoKRsHAAQJZg4AeDCkAk5YAQ3icYxgFo2BYAkZUQJZWGjltEAEAHPAAGXicYxgFIx4wogLy9VPfaaOAxgAAMNMAGXicYxgFpABGZECpGdR02CgYBeQAAD8gABd4nGOgGWBEAlQxh0ruGgWjYJAB6mQUsrILAFPUACl4nGMYBaNgCAFGGKCyeVQybsgBABeQABJ4nGMYBcMVMMIA1c2kooGjYGABACIAABB4nGMYBUDACAM0MJfKRo6CUUBFAAApKAAOeJxjIBUwwgDJOokymeqmjoJRMECAdlkFajgVjAEAPhgAHHicYxgFo2AQAEYooNQU3KZTZvJwBQAWaQAPeJxjGAVDDTBCARWMIU1iFAw/AAAmDAAReJxjGN6AEQKoYgpOGQpNHwWjYMAAADigABN4nGNAAEYwQBIgB0AMwW4MFYwfBaNgEAA8iZz0rILdGDplFgBS7QAneJxjGAWjgKaAEQyoYQZOg6hgw0gFACJpABd4nGMYBYMIMIIBFYzAYxDFNoyCYQQANMEAF3icYxiygBEMKDcBCnCroMSKUTAKBgHAnY4BTVMAHnicYyAOMCIDPEqING4UjIJBCyhMx0RklUGUVwBXGQApeJxjGAWjgHzACAKU6YYDmlgxCvADAChWABl4nGMYBXQDjEBAiV4EwKuKXCtGwQgEADmvABh4nGMYpIARCsjWCAd4FVLixFEwCgYHIDbJY9EAAGc+ADl4nGNEBgy4AH7ZUTAKhg5ASfFkAwLm0803lAIAjqsAXnicYxgFowAPYKQUEDadPh4ZBVgBAH1AAEd4nGMYBdQGjOQAIs2ltdtHwQgDAJW9ADp4nGMYJICReEC0cTR28igYBYMRkJRVAKccADx4nGNgYGAEASA9CkbByALglA8FJOigqZvoDAAn1AAXeJxjGAWjgDBgRAak6KGlo0YB5QAAI+YAE3icYxgF1AWMyIA0XbRz1CgYBdgBADLoABN4nGMYOMCIDEjVRytHjYJRMOgAuTmFiLwCAEbWACV4nGMYBaNg+ABGZECOXlo4ajADABfuABN4nGMYBSMTMCID8nRT31GjgN4AACbwABN4nGMYBYQAIzIgVz+1HTUKRgE1AAA18gATeJxjoCJgRAHkG0FNN42CUTDoAGpGITe9UyWvAABRswAoeJxjGAWjYNACRjRAmUHUc9fwAQAfGwAWeJxjGAXDATCiA0qNoprLRsGgBgA0xgAYeJxjGGGAER1QwTTquGwUjAJqAeITOABJuwAkeJxjwAUY0QFOlUQC6pgyCkYBxQAjbWMB5BtGNQdSwSCCAACM3QBTeJxjGAWjAA0wUgBIMZaKrqWOUSMQAACQ7wBTeJxjGAXkAUaqAvxGU9fRVDNtFAx9AAAD6gBleJxjoANgJA6QrAGfEVRyNTUNHAWjgACgLG2Tk1EAaSwArXicY6AKYAQB6hg1CkYBMQCc5JAA1QzCCajpcCqZRTkAAFLGAER4nGMYBcMdMCIAFY0iGlBsH6WOHgV4AAB7YgBFeJxjGAVIgBEBqGoYkrFYRbEpJMs6yl09CkYUAADJNgBOeJxjIBMwIgC5RuA0EIuZqLI4AImWUcfdo2AU4AdUzyrkZips2QUA7r8AbHicYyAIGEGAsLJRMAooBuC0NvAJDuEMJEC0Rho7jroAADt4ACp4nGMYBUMSMCLAQDsFDpDcRISrBpfbRyoAADpLAB54nGMY/oARDgbaJZiASKcNUtePgiEPAEUSABl4nGNABowIgCJOMaCWwcSYgmQX1f0xCkYBBFAxiaEmWAxAy+zCyAgAt1UAY3icY0QBDKNgFFAZUCV5oSZTAoBiS4hzA7nWDCoAAJtHAGB4nGMYBYMHMCIAVQwhGlBoERHOIN8/o4CWAAC0yQBZeJxjGKKAEQ6oYQZWgE8dzVxMmY9GwSjABPgSHgDaOABUeJxjIA4wogPSVBPSgNcM/EpINXcUjAI8gMzUSlrCJSbHUNlWXFIA1xYAZ3icYxgFo4BMwAgGlOon0xAkzeQYgFcjZd4aUgAAPogALnicYxgFdAGMIEChdsrMQBhBhiG4dVLosVEwsAAAWi8AKnicYxh8gBEMKNNNkRHoRlHgCCzClLpqFIwCOKAooYO0AgB4fQAyeJxjhAAGUgBUDwygi5NkFqqB6IKkGzUKRgEOQG7qRE3xZGYSfIBc16CJkGoMGAAAyoYAdHicYxgFowATMIIB+TqJ046klhJAnC0oXHJ8NiwBAJBHAGV4nGMYBZQCRhAgWyNEN24TEIpoB7BZiOCQ47VRMEQAACDKAIJ4nGOgL2AEATK1QQCMg0seFyBVPVEAbhQFfhsFowArIC89oaV4BA97CgYAsSoAu3icY0QBDEQBVD1kAKgRxNk2CkYBQUBWesJM98QlXrKsIT8LgRWTbCuRAACEhgC+eJxjGAUjDTCCAFmaIBrhTNyAUtcRNoFW1o80AACI5QBWeJxjGAX4ACMIkKeLIKDARRQYRTWHjILhAADLGQBUeJxjoB5gBAGSNRALaGAkcWaS7ZZRMApwAJKSEbHJmNg0iqIMAIV2ALZ4nGMkHTAQAmRoGQWjAAcgJQWRlGiJSKJk5A5S0z5ZOYx6AAB8wgDMeJxjGAXDCDCCAQlKUQApWogwjkxAyAFYrCLKw6MAGwAA3q4Ah3icYxixgBEMiFcJBVA+qfpwmIaQwxTGqg67ZlyWIxxLjJZRMPIAADnEAH94nGMgCjCCALHqUBQTqxNVN0gLMg/FCFQJnACHyXi9h6QCv45RMApwACLTDLb0RUpqIyb5E5FLAJRPAMt4nGOEAAYUABXElIDJYTDxahkFowA7IC69YE1axGhFSpQkAGJMIzK/IIugyg6W7AIAB+oAm3icYxgFQwUwAgExaiCAJK0IbaQDogzFJYEuipWDU8sooBgAANxFAHt4nGMYnoARBIhQgk0ZPq1wTZQAwkbjksHhPQw9BC0bBaMADABWigCDeJxjAAJGIADRuABIHgKwS+HXgwxwSuADBNyEoQRNFEMBFjMJ2TYKRgEEEEgjeNMR7hyENS2jC1KQXXArAQD0rQDteJxjYGBghAAgC8IEMeAAUwShA5vUKBgFcIA3geBPQ1gkkFIduiw2UXTluAAuV+NSABPDJzd08gsA90YAmnicYxgFgwMwggA+OTwKMGUQOtD1IgtgU0UMwOZsHE5EsogIZ2M6cRTQFgAAGa0AknicYxiSgBEIcMuAAfF64VpoBrDZjdWZeFyPx1NYLBoFowAGcCYMkAQAoEAAn3icYwQCBtwATRrEpQrAbx4Wu1G0oekm7G6s2vD7fBSMRIAzVRCTYFBUUJo1UE3AlYDxaiXGAwAijAEGeJxjAAJGEAAxsAOwNAE1o2AEAlxJgrjEglCDSGDkAMxkim45fn1YHYzHB4Q8h8sVgxMAAOaXAJp4nGMYBXQBjCCAS4I47XBjKATILkITw5TAKY+hHr/D8QcMPhNGAS0BACZCAI94nGMYjIARCHCJY5XAoh2slmYAzU24paHy6KpxO5yQ/7BaMgpGLMCVFIhMIgDIKwCoeJxjYBwMgAEGkPlYpFEAHik0RcQoHAUjAOBICEQnENzpl8oZAj9Acw/CZwRyCxZhALITAUZ4nGNAA4wQgC48CkYcwJUOiE0e0JSEAnDLoKnBr4Q0gOYihM9w+4ToPDDkcwsA9b4AqXicYxgF1ACMQIBDGJs4VnVIALcMQh6VQTWAzWYCXiHWl6SoHAX0AQBTAwCdeJxjGADACATYRbEIY1cHAzgl0GWhfEw1xAI0rVAupu34vEhIiswQGQXDF2BPA9TLKwC1OgCxeJxjZGRgYGAEASANB2ABqgMMC5A4yLajq8MhR77SUTA8AdYUQGy6wJVUkSQwLSEl2ZOdW1AE8PmGhBwAMxEA/LIA/XicYxgFIxMwggBWUWI1M2IxAyIBF4Uz4eLIgDhbiAPYHYDPFiK9iiewhgMAALIPAHp4nGMYBUQARiDAKogpilUVSB26cqgEXBDBxwREOpFogOwBuAA+i4h0BCkBMwoGAwAAJCYAgHicY6A6YAQBogSxawUrRFUPE4fJootgSBNlDwFz0EyEMpA14jOeCFeQpXoUDCtAtbwC04El9eJN2gCcFADGeJxjIAQYwQBKEQNgerDQuMwn6AhU1xCvfBQMJ4At7olJDxhJE6KFiJSMxsBrOjEmYrEDYTCyu+BmU5JZiMktAIGCAOJ4nGMYBcMTMAIBFiF0MWzaIACJgyyMhY+sE5WFYSgVAKpfUEUIhQBhr5OiYTgAAAduAKZ4nGMYBUDACASYImhCWHVBACoPVRxZDpWPSxcRgEitaL6BC2H6jgjvkh5Ao2DQAwCRrQCneJxjIB0wAgEhEayaIAChAyGGagCKALouUgAuJxBQDOFBxbAYhcVsQoAMLaNgOAAyMgs0waFlFtTki5GokXUSldyhAAAH3wDzeJxjRAEMSABVBgOgKAOTcC3IpkBlSAOYpoyCkQAwo51QQoAlOLg6JD5GokYWQpMjkNgJ5gKsRmBxBaYcxZmFstwCAJqJAOt4nGMYBUMUMAIBIREMabACGA3XAJGBC8OFkEm4FJJiDIAsj1UxumuQpTBUYjWeaO/iCwXStQ1XAAAQ0ACheJxjGBmAEQgwBFBFMKUh8jAGlIbIoGiHcnDJALlIUijWIoRQVWCoxC6NohSXVhwBQBwgEEyjYKgDAJPuAKF4nGPAAhiBAL8ATvUwJohGBUgKQGzsEhQCZAehSxGjj0j/EhMQo2CEAAozC9bcgkseT/omB4CMAgBiGAEieJxjYGDEAAzYBJEkUQFWQSIAufpGwdAFGHGOPxGgJDgYG5ESkRIkBhODRznAbhyS7YTzyuDLLAB1EwDgeJxjGAWDFTACAX4B3LJwDogBYcNoqBBCHY0AVsNR7MeQIRQA5AbcKMAJADl7AKx4nGMYJoARCPAL4JYFcUA8MA0RRxVCVkc2IEM/sgMwpQgEALkBNwqGPUBKQQDQWwC1eJxjAANGIICwsAFUWSgPREHFoSyoCIo0KsAuilUlinVEa4Ey8BpI2L/EhsQoGBEAPdLxJgIsqRdbZiEmNROd8onILRgSMMUAgocBQHicY2DEDhgQAI1LNCBX3ygYwgA90vEmAqwJDTkF4kicGImVSHVoqZt4o7EpRhUZqpkFAE1BAN54nGMYBQMHGIEAHx+fYhCXEUKismgBMKzDpQ5ZNaoBaIKE/UtCuI0CsgEAgwoAyHicYxgygBEI0LjIfLyKIXywFgyAZByVANx2ohRjUYXNSRheIjPcRsFIAFgyC3aFABtQAMx4nGMAAkYgANEwAOaDCCwAroB8gEU7wl6SDEJ1OXZDSQNkaxwFQxegxTneJICRQNBSI460TnaWgWpEsQdHesdrFY5szggA20oBZXicY4QBBjIAufpGwdAFaHGONwlgSiJSGzzhoXFAfFQu6QBuIBab0azGrh2rvzAVDYPMAgARVQDAeJxjGAU0BIxAgJuLVy1UBCwIZcBVIPEpBzDjMOyFCWKoRHcOLn9hUUlmwI0CWgEAY34ArHicYxg8gBEIcHPxqoWKgAShNISDLIMqgUUQG8ChDs1SZGEkNnZNuPyFwwrSA24UjACAJbPgTANY5ODJDAD0+ADDeJxjZGRghAAGEICykQFWQawAu0KwudgMwW4dpi4oEwVgWodNFU6do2BEAfQ4x5MGsKUlbCkcR+IlOq+QDHBYiJHF8Hgfmx4Ao8YBW3icY8ALGIEAv4pRMNwAepyD+DgSAVYZsHqwBIyFAZBUMeJWRRqAmQNzLx6VeNM2mgp0XcMtswAAD3AAwnicYxgFlABGIMAvgF8GJAgRB1NQLhqAK0NiUQXAXYVXCR5voQpj00h0wI2CAQEAkgUAunicY6AjYAQCDAFUEZxKYarB4hAKxkcDMHEkHVQBRJiHx/E4vY+ml+jQGAXDG2AmClypAGvyQc0OGGkXLgAAQU0A7nicY2AEAwYoTUfAAAZITBSATRiLdiJ1joJhDjAinZR0hZb2MQTQswfxeQW7SmyWYlOErgNn0sbjV/z5hZERAI3WAUd4nGNkZGQYBSMLAOMcLdYxReDC2HXDAKYIRBTBxJDECbApxWopVnXoenB4CYencPiMiDAa4gAAGX0Au3icYxgFBAAjEBASwSkKEgQKQykkIRoANEvxqkTTg91HKM7GKY1uO1wGp75RMHgAAKCuALd4nGOgLmAEAQIiMFFcusEkVBbCpjpAto+wYlRd2D2E4mp8gYPmBJzmjYLhDzBjHltawJfgUGRREheROQEAUw0BBHicYyQMGIiTQVPGAAYIFjJAVoEHYJpHnL5RMBwBZtxjSw04EghUKXpSwsalAcC0AFtmwZ64icwrmPmFOH0ANOYBLHicYxgFwxIwAgGmCBYhHHqB4mAKrADKQlaOJEQ1QKTZODwD00daGGGxfkQBABipALJ4nGMYBQwMjCCAKURIBFkvmEJhoShHEqQKINpcXC5HdyDRwYTpt1EwhAEAojoArnicYyAdMAIBpgiKEIYAqjiYAjORSXR1lAGEIdjNxGYJDpejGENiQCGbPQpGHsAS99gSOx6tiByClFmQNZCTO+CmAQA+LQENeJxjBAEGMAlhggCCCxdEFwKLwjUgAJIpJAIslo6CEQYw4x09KeBKGdA0g0iXqAkbVyIjBWDoRjUPxsZuCYZHKMkqUMMwXEMGAAC8swEEeJxjGAVDFTCCAKYQbi6qTkaYNIQH5cM5CHGyALp27KbhswWbiykLJjzmj1gAAEAdAL54nGMYKYARCDBFkIQwFSApY4RLQ7hUBcQZimQ5pnosDiY3kBA6cVsxCoYLAADhnADAeJxjwAoYgQCLEEIMiwKEKka4NISLJEhTgGQfkuVozkBxN6YI8QCLTlzWjILhDLDFNgmZBT29YqRlKmQi7DkAxAQAmkUBPnicY2RkZAABIA1lQlhQAJaDAAwBEgAOrbisGgXDF2CJapTox5UW0FIKhIEphJqiMIRIBRjW484rmI6lal6hUX4BAFlKANp4nGMYBYMYMIIAFjHsHDR9EIBsDKYgskJ0ARIBpu0oTJzK0XVTGj7Yg4FsK4Y5AAA8KACveJxjGEaAEQiwCMHFsMgjFMFVQhkIQXQe5QCLzUh2YLMMWTkFoUNALw5XjoJhCKBRDADdjQC7eJxjQAaMQICNja4GApCUgUmEDAaPfIBpLdxC/JpQtZMIiNSL1aWjYBgCLBGMHOukZxaUxEMoPeNK5lhTPhGqkAAAmJ0BUXicY0QABvIACXopt2wUDAGALYKRoh1X9COlDpA8hIIrRpJCUUJbALEfiU23vIIeajQCADMLANJ4nGMYBQMMGIEAmxhEGJssshKoOmQSQxomjC5GXQBzLDabyQ0XkjRTZt0IBQBYoACxeJxjGFqAEQSwCoLEscoiq0Aog4hhlYcIowlRFWCzE6fbyQ4WQurJt24UDA2APY5RsgEA8VcAwnicY8AEjJgALIZDHocW6gCcLkJ2EGmARK2UWTYKhgzAFcv40xtqFkFiIckjp1+aZhZcmQRPAgYAkHsBS3icY8ALGEEAvxJ01STpGAVDFeCKZvxpACGJUIekGMqEy6EopAMgJ9GTl1cGTVYBAA5MAL94nGMYBbQHjCCAWwaHJJIcnImkGMKCydANwK0k6DeyAgR3MJBsySggAgAAbeYAsnicYxh8gBEMcMtglUWWgLMRKhF8egIM3+D0GaHgICnoSLZiFAxdgCfC0VIi1mQCAAVOAMt4nGNgYGAEAwgF5EJFoMK0B3ALEU6BAhQOUYAEHcjWj4KRAvDEOUaiRJPAVIZFHy0BehpHcymJqRmqGwB5TwE4eJxjIAIwQgExakfBMAJ4oh2WJtCTBhofQwmaPloBZPuxeoWE9ExK8h9yWQUADZAAtXicYxgFVAOMIIBLAiILBwgNSFrQpNG0UAhQjEM2H9WZ2DyCy19YAwBnKOBSTYzaUUAjAABuNACmeJxjGDDACAY4xOHyMADnoxuAEEXVABLEECEOoBqG5iwMLro3sPsKq+dxBQFO5UQoHQXDEuCIfyRRnEkZmzScCwD+dgDceJxjJAgYsIkhAwxxDDVoUlhlcAHc9uJXT4TSUTBcAY4kgCKIN1UTzhZEA7xZBYtL4Xx0KULJmtScAtYAAOwKAQF4nGMEAoZRMKIBKA1gpgIMMYgyOMAtQwHAbiYKF8NJWL2AN13j8gehIBqGeQUA/KwAo3icYxgFpAJGECBWDBngEMYOiFaI3xAsTsQuhcev2EzDHzrEKx8FAwsAi+AArHicY6A1YAQDTDFcKskCMFsoMQLTJSgskhxPStAQr34UDHuAJTngTB9kZxOktM0AADXwAPt4nGMkBzAgAbgQNkmwIIoAQh0W1TgByRpGwUgAOFIjwTREXBInTQOhfIJkIJLReN1OTk4hNasAAO9XAQx4nGMYBSMFMIIBugg+tXQBeO1HcQq6PC7nkhQepOgYhgAACZ8ApnicYxgFOAAjCKDx8ahEU44QIxNgNwOP9Wga0KSxuou0sCBRzygYCgAAb08AmXicY6ASYAQDFC4+hWjKUUSJBbj14bQfSStWdyBzMewiIRxI0zMKRhpATSB4UguONEhSHsGrGgD7BADzeJxjZGBgYAQCIIUGQKIQCSgLIYAkj6QSVZowIEvTKBh5ADPdEUxQKEpQ0y/5AG4WrqyCXQuSD8jLKWRpIhIAAFx1ANV4nGMYBcMMMEIAEgenMphaNCVwUfIBkh1YXYesFM0NOE0j1uck6hrZAAAJ9wCdeJxjGOmAEQrgbFyKEErRlMCFyQHoduA3mKBlpPmZNF2jYBgCAImNAJ14nGMgDTDCAZSNSw2SUpxGkAkQVlBiKGm+JUnbKBgFYEBM6kFO0diUkJ6yCSR4VFEAU2EBHnicYyQMGAgC8nSNglGAAggnIZgobiVEpGeaAPJ8OPD5BAB74QDgeJxjGAVDFjCiAKzSqAoJGYETkKoehwm4XEGUs8gIoFFAEAAADjIAlXicYxhBgBEZYJNDVUbIBIga3Ebi04cJkNShM0kzl5iQGAWjAAIAQWQAenicY8ADGJEApgy6IgIGINRhCBDSgd14hDBO+/Gai1f9KBgFJAMcqQuFizf54U79RAN8LsOWVwDGRgDgeJxjQAaMWAGKklEwCqgFsCUytBSHOxFCRbEnWWIAfjchmLjdTJSBgxwAAOnbAJp4nGMYBUMFMCIDhBBWJVi0YjOFKEDQOQgOUTZQKzxGARUAAPpjAIJ4nGMYroARFcBEcKhBF0RhohmFExDjEuJNw2neKBgFVAMAdi4AiHicY4AARnQAEYHKYijCFMEvjmYUptE4tREG2AwaBaOAhgAph+BJidRJt9jVUi2LAADuWgDleJxjGAWjgLaAEQRgNBxgV4YDkGIV0YaSZcNwAwB5FwBdeJxjGAWDCzCCAII1iMDAhssooAkAAEDIAJZ4nGMY2oARDJDZAw4GNDxGwSjADVBTKJgNAKWjAJp4nGOkN2BgQOGMglEwSAF6IqVrJsGwk0aeBAAjxwD6eJxjGAWjgBqAEQaQ+QSUomkhxRYsWskxb8QDAFcGADt4nGMYBQMCGGEAwcWrDBsg2g5MxUSbMQqGNwAAlZwAQXicYxgagBEOYBycSlBUYwP4TMcmj0fjKBgFgxEgJ2YsSRdJFgDx7ABleJxjAAJGogBIJZpSsBAywC0zCkbBoAVIKRo99eJK0cTlGSJyygBnFQAqjgCPeJxjGAWjgETAiAFQhUnSisMwrDpo5qORCwB5GABMeJxjGAU0B4y4AQUmQETxKaKBV0bBMAMApWYARXicYxh8gBE7IN8kOJuADWTZMQpGwYACypIxAMLaAE94nGPAChiBAM7AC7DrHwWjYJAC6qdfsDHYTR38OQYAuZgAW3icYxgFowAfYIQBKhuH3VR0aepZPAqwAgBJUQAueJxjGAVUBYwYgFpm0cHCUTDiAAB8uQAzeJxjGFjASAQg2RQS7aSGP0bBKKADICa74M1AGBIA7FoAiHicYyAGMKIAorSMglEw4AA13VIGyLaYNl6jFgAAjJcAZ3icYxgFowAdMFIAwJopsZAG/hkFOAEAiFIATXicYxgFNACMRACEQsrMp67LR8HIAgCJIwA2eJxjGJyAERmgiFJsHJVcOApGwaAGxCV2AGL3ACN4nGPABhiRAFYFo2AUDC9AUVofwrkFAD6xABx4nGMYBaOAZMAIBhRqp8SEUUAlAAAcbAAQeJxjGAU0B4xgQLEBlJgwCkYBVgAAJAEADnicYxh0gBEMKNVPgQGjYBQMGQBN7eQkd7A+ADClABt4nGMEAYZRMApGBAAndxLTPELPMMwrAC4uAB54nGMYBaMAF2BEBiQqJ0rHKBhoAAA3AQAeeJxjGAXUAoxYATFq0FWNglFAJwAAeysAL3icYxg4wEgOGED3joJRMKCAFvkEAMPlAGJ4nGMYBaNguAJGIsBAu3GAAQAqdgAleJxjGAWjAA0wooGBds8ooB0AACJIABF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBaNgFIxYAAAEAAABeJxjGAWjYBSMWAAABAAAAXicYxgFo2AUjFgAAAQAAAF4nGMYBSMIAAAB7gAB
// //                     </DataArray>
// //                 </PointData>
// //                 <CellData/>
// //             </Piece>
// //         </ImageData>
// //     </VTKFile>`;

// //     const fileName: string = "myVtiData.vti";
// //     const fileOptions = { type: "application/xml" };
// //     const file: File = new File([vtiFileContent], fileName, fileOptions);

// //     return file;

// // }

// function generateSegmentMetadata(
//     parentImageID: string
// ): SegmentGroupMetadata {
//     const order: number[] = [];
//     const byValue: Record<number, any> = {};

//     for (const key in DENTAL_CLASS_MAP) {
//         const value = Number(key);
//         order.push(value);
//         byValue[value] = {
//             value: value,
//             name: DENTAL_CLASS_MAP[value].name,
//             color: DENTAL_CLASS_MAP[value].color,
//             visible: true,
//         };
//     }

//     return {
//         name: 'Dental Segmentation',
//         parentImage: parentImageID,
//         segments: {
//             order: order,
//             byValue: byValue,
//         },
//     };
// }

// async function fetchApiRulers(dicomData: DicomImageData) {
//     const {
//         studyInstanceUID,
//         seriesInstanceUID,
//         sopInstanceUID,
//     } = dicomData;

//     const response = await fetch(`${VITE_FASTAPI_URL}/get_segmentation`, {
//         method: 'POST',
//         headers: { 'Content-Type': 'application/json' },
//         body: JSON.stringify({
//             StudyInstanceUID: studyInstanceUID,
//             SeriesInstanceUID: seriesInstanceUID,
//             SopInstanceUID: sopInstanceUID
//         }),
//     });

//     if (!response.ok) {
//         const errorText = await response.text();
//         console.error("API Error Response:", errorText);
//         throw new Error(`API Error: ${response.status} ${response.statusText}`);
//     }

//     const segmentationBlob = await response.blob();
//     return segmentationBlob;
// }

// function getDicomImageData(currentImageID: string): DicomImageData {
//     const imageCacheStore = useImageCacheStore();

//     // default value
//     const data = {
//         studyInstanceUID: "",
//         seriesInstanceUID: "",
//         sopInstanceUID: "",
//     };

//     const image = imageCacheStore.imageById[currentImageID];

//     if (!(image instanceof DicomChunkImage)) {
//         return data;
//     }

//     const metaPairs = image.getDicomMetadata();
//     if (!metaPairs) {
//         return data;
//     }

//     try {
//         const metadata = Object.fromEntries(metaPairs);

//         data.studyInstanceUID = metadata[Tags.StudyInstanceUID] || "";
//         data.seriesInstanceUID = metadata[Tags.SeriesInstanceUID] || "";
//         data.sopInstanceUID = metadata[Tags.SOPInstanceUID] || "";

//     } catch (error) {
//         console.error("Error parsing DICOM metadata:", error);
//     }

//     return data;
// }


// export async function getSegmentation() {
//     const segmentGroupStore = useSegmentGroupStore();

//     try {
//         // get currentImageID
//         const currentImageID = useCurrentImage()?.currentImageID?.value;
//         if (!currentImageID)
//             return

//         // get dicom data
//         const dicomData = getDicomImageData(currentImageID);
//         if (!dicomData || !dicomData.sopInstanceUID) {
//             console.error("無法取得 DICOM 資料或 SopInstanceUID");
//             return;
//         }

//         // get vti File
//         const segmentationBlob: Blob = await fetchApiRulers(dicomData);
//         const vtiFileName = `segmentation_${dicomData.sopInstanceUID}.vti`;
//         const vtiFile = new File([segmentationBlob], vtiFileName, {
//             type: 'application/xml',
//         });

//         // input vti File
//         const vtkImage: vtkImageData = await readImage(vtiFile);
//         const labelmapImage: vtkLabelMap = toLabelMap(vtkImage);

//         // generate lebel
//         const metadata: SegmentGroupMetadata = generateSegmentMetadata(currentImageID);
//         const segmentGroupID = segmentGroupStore.addLabelmap(labelmapImage, metadata);

//         console.log('Segmentation added with Group ID:', segmentGroupID);

//         // const vtkImage: vtkImageData = await readImage(getVtiFile());
//         // const labelmapImage: vtkLabelMap = toLabelMap(vtkImage);
//         // const metadata: SegmentGroupMetadata = generateSegmentMetadata(currentImageID);
//         // const segmentGroupID = segmentGroupStore.addLabelmap(labelmapImage, metadata);

//         console.log('getSegmentation')
//     } catch (error) {
//         console.error('Failed to get or process segmentation:', error);
//     }
// }